name: Deploy Frontend on Github Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Set up JDK 1.8
        run: npm install create-elm-app -g
      - name: Move to Frontend directory
        run: cd Frontend
      - name: Show content of Frontend directory
        run: ls -al
      - name: Build an app to build/ directory
        run: elm-app build
      - name: Deploy
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build
          SCRIPT_MODE: true
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
          bash ./entrypoint.sh

