name: Push API to Docker

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Set up Docker
#        run: curl -sSL https://get.docker.com/ | sh
#      - name: Login to DockerHub
#        env:
#          secret_email: ${{ secrets.SecretEmail }}
#          secret_password: ${{ secrets.SecretPassword }}
#          secret_username: ${{ secrets.UserName }}
#        run: docker login -p eEkXbAV8YN99FYN -u inql
#      - name: Change permissions for .docker directory
#        run: sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
#      - name: Push API to DockerHub
#        env:
#          TZ: Europe/Warsaw
#        run: sbt docker:publish
      - name: foo foo ls
        run: tree /
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ../task-definition.json
          service: start-owl-service
          cluster: my-ecs-cluster
          wait-for-service-stability: true