name: Perform tests on API and deploy to Azure

on:
  pull_request:
    types: [assigned, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Docker
        run: curl -sSL https://get.docker.com/ | sh
      - name: Run tests
        env:
          TZ: Europe/Warsaw
        run: sbt test
      - name: Login to DockerHub
        env:
          secret_password: ${{ secrets.SecretPassword }}
          secret_username: ${{ secrets.UserName }}
        run: docker login -p $secret_password -u $secret_username
      - name: Change permissions for .docker directory
        run: sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
      - name: Push API to DockerHub
        env:
          TZ: Europe/Warsaw
        run: sbt docker:publish
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'StartOwl'
          images: 'index.docker.io/inql/start-owl-api:latest'

      - name: Azure logout
        run: |
          az logout
