name: ELM-CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Elm environment
      uses: JorelAli/setup-elm@v1
      with:
        elm-version: 0.19.1
    - name : Elm Make
      working-directory: ${{ github.workspace }}/Frontend
      run: elm make src/Main.elm
    - name : Find directory ls 
      working-directory: ${{ github.workspace }}
      run: ls -l 
