name: Scala API Test

on:
  push:
    branches:
      - 'feature/**'         # Push events on master branch
      - 'bugfix/**' # Push events to branches matching refs/heads/mona/octocat

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      env:
        TZ: Europe/Warsaw
      run: sbt test
